name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        cmake_version: ["3.0.2", "3.1.3", "3.2.3", "3.3.2", "3.4.3", "3.5.2", "3.6.3", "3.7.2", "3.8.2", "3.9.6", "3.10.3", "3.11.4", "3.12.4", "3.13.5", "3.14.7", "3.15.7", "3.16.9", "3.17.5", "3.18.6", "3.19.8", "3.20.6", "3.21.6", "3.22.4", "3.23.1"]
        build_type: ["Debug", "Release"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: ${{matrix.cmake_version}}
      - name: Run Tests
        working-directory: tests
        run: |
          mkdir test_build
          cd test_build
          cmake -D CMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} ..
