name: Static Analysis
on:
  pull_request:
  push:
  workflow_dispatch:
# Adapted from https://stackoverflow.com/a/72408109
concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true
jobs:
  support_files:
    name: Support Files
    uses: brobeson/SupportFileQuality/.github/workflows/support_files.yaml@v1
